// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"todo-tasks/internal/domain/todos"
)

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool  `json:"hasNextPage"`
	HasPreviousPage bool  `json:"hasPreviousPage"`
	Quantity        int32 `json:"quantity"`
}

type PageInput struct {
	Limit  *int32  `json:"limit,omitempty"`
	Page   *int32  `json:"page,omitempty"`
	Search *string `json:"search,omitempty"`
}

type Query struct {
}

type TodoInput struct {
	Text string `json:"text"`
}

type TodosResponse struct {
	Todos    []*todos.Todo `json:"todos"`
	PageInfo *PageInfo     `json:"pageInfo,omitempty"`
}

type UpdateTodo struct {
	Text *string `json:"text,omitempty"`
	Done *bool   `json:"done,omitempty"`
}
