// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool  `json:"hasNextPage"`
	HasPreviousPage bool  `json:"hasPreviousPage"`
	Quantity        int32 `json:"quantity"`
}

type PageInput struct {
	Limit  *int32  `json:"limit,omitempty"`
	Offset *int32  `json:"offset,omitempty"`
	Search *string `json:"search,omitempty"`
}

type Query struct {
}

type TodoInput struct {
	Text string `json:"text"`
}
